version: '2'

services:
   web:
      image: php:7.2-apache
      restart: on-failure
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "80:80"
      volumes:
        - ./web:/var/www/html/
        - ./logs:/var/log/apache2/

